### ISSUE TITLE
Error trying beegfs_local_ssd example.

### ISSUE THREAD

**Issue by tmefford** [Azure/azurehpc#148]
After running azhpc-init azhpc-build fails with this error:

Thu Jan 23 09:29:47 PST 2020 : creating vm: beegfsm
az vm create: 'os=StandardSSD_LRS' is not a valid value for '--storage-sku'. See 'az vm create --help'.

**Comment by tmefford** [comment]
Tried the lustre_full example--same result--
Fri Jan 24 09:52:30 PST 2020 : creating vmss: compute
az vmss create: 'os=StandardSSD_LRS' is not a valid value for '--storage-sku'. See 'az vmss create --help'.

**Comment by garvct** [comment]
Looking into this error, stay tuned.

**Comment by garvct** [comment]
The beegfs_local_ssd example deploys for me correctly.

I wonder if you have an out-of-date azurehpc repo?
or 
your az cli is too old?

my az cli version is azure-cli                         2.0.80

What is the version number of your az cli (az --version)?
If it's old please update it to the latest version.
Also did you pull the latest azurehpc repo?  (git pull)
If the az cli and/or azurehpc repo is out-of-date, please update to latest version and try deploying again.

**Comment by tmefford** [comment]
Could be,  2.0.46 is what I have currently.  Do you think that would make the difference?  I just did a git clone on the repo early this week, so that is probably up-to-date.  I will update cli and try again.   Will update on Monday.  (Don’t want to leave cluster up over the weekend.)  Also, (Please don’t stop listening!!)  I did have to make a couple of changes to the config file for what I need to accomplish.  Nothing I can easily believe would create the error I am seeing, but if an upgrade fails to solve the problem, I will try the example as is.

Thank you for looking into this!

Tim

**Comment by garvct** [comment]
Hi Tim, yes I think the version you have for az cli is too old. You can verify by

az vm create -h | more

search for the "--storage-sku" command option my description says

"The SKU of the storage account with which to persist VM. Use a
                                     singular sku that would be applied across all disks, or specify
                                     individual disks. Usage: [--storage-sku SKU | --storage-sku
                                     ID=SKU ID=SKU ID=SKU...], where each ID is "os" or a 0-indexed
                                     lun. Allowed values: Standard_LRS, Premium_LRS,
                                     StandardSSD_LRS, UltraSSD_LRS."

I suspect your older version does not support the newer syntax "os=StandardSSD_LRS "etc

Thanks,
Cormac.

**Comment by tmefford** [comment]
I think the new version mostly worked to fix the issue.  Sorry for the trouble.  The cluster creation failed, but I'm not sure if this is even a bug.  Any suggestions would be appreciated--thank you, Tim

Mon Jan 27 10:59:40 PST 2020 : creating vm: beegfsm
Mon Jan 27 10:59:50 PST 2020 : creating vmss: beegfssm
Mon Jan 27 11:00:03 PST 2020 : creating vmss: compute
Mon Jan 27 11:00:16 PST 2020 : creating vm: headnode
Mon Jan 27 11:00:29 PST 2020 : waiting for beegfsm to be created
Mon Jan 27 11:01:01 PST 2020 : waiting for beegfssm to be created
Mon Jan 27 11:04:37 PST 2020 : waiting for compute to be created
Mon Jan 27 11:04:39 PST 2020 : waiting for headnode to be created
Mon Jan 27 11:04:40 PST 2020 : getting public ip for headnode
Mon Jan 27 11:04:42 PST 2020 : building hostlists
Mon Jan 27 11:04:45 PST 2020 : building install scripts
rsync azhpc_install_config to headnode60f349.westeurope.cloudapp.azure.com
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9]
Mon Jan 27 11:06:53 PST 2020 : running the install scripts
Step 0 : install_node_setup.sh (jumpbox_script)
Error: (255) Errors while running azhpc_install_config/install/00_install_node_setup.sh
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(605) [Receiver=3.0.9]
Mon Jan 27 11:11:08 PST 2020 error : There were errors while running scripts, exiting

**Comment by garvct** [comment]
It  looks like you may have some network issues? The error occurred when azhpc tried to copy some scripts/env from your local WS to the headnode you created in Azure.

Can you ssh to the headnode?

ssh -i <YOUR_KEY> hpcadmin@headnode60f349.westeurope.cloudapp.azure.com

**Comment by tmefford** [comment]
I could, but then I deleted it all in order to try again.  Perhaps being behind a firewall is biting me here.  ssh can go through, as it is set up with a proxy, but perhaps the scripts need to have a proxy set somewhere else.   Or maybe they need an http proxy.  Thanks for looking the error message over.  I will try again this afternoon.  If there is a place to set a proxy, please let me know.   Thank you--Tim

**Comment by tmefford** [comment]
Failure in same place.  I think it is proxy related.  I've succeeded in copying the azhpc_install_config scripts over.  Just run them in order?  Sorry to clutter the issue database.

**Comment by xpillons** [comment]
I would suggest you to use Azure Cloud Shell as it comes with a full working AZ CLI environment. Just clone azhpc from there, you can use "vi" or "code" as editors.

**Comment by tmefford** [comment]
Thanks for the follow up.  I will try this and use that as a backup plan if this fails.

**Comment by garvct** [comment]
We deviating from the original issueraised. If you still are having problems, please open another issue.
