### ISSUE TITLE
ib0 ip address setup

### ISSUE THREAD

**Issue by tbugfinder** [Azure/azurehpc#167]
Hi,
I'm wondering if there's a common module for setup of the ib0 interface esp. for SR-IOV vm types.

Thanks.

**Comment by garvct** [comment]
If you use the Azure Marketplace image CentOS-HPC 7.6 or 7.7 (preferred), it will come with Mellanox OFED drivers installed and a number of MPI libraries will be preinstalled (openmpi, hpcx, intel mpi and mvapich2). This works well with HPC VM's like HB, HC and HBv2 (all support InfiniBand via SRIOV). You can access the different mpi libraries with module commands (use "module av" to see what mpi libraries are available).

**Comment by tbugfinder** [comment]
I'm using CentOS-HPC 7.7 however I don't see an ib0 interface. What do I miss here?

**Comment by chadnar2** [comment]
It would be interesting to see if the device shows up. Are you able to get output from running 'lspci |grep -i Mell' ? I assume already that 'ifconfig' does not show the ib0. This may help determine if it's a software issue.

**Comment by xpillons** [comment]
On which VM size are you running ?

**Comment by tbugfinder** [comment]
This is HB60rs:
]# lspci
0000:00:00.0 Host bridge: Intel Corporation 440BX/ZX/DX - 82443BX/ZX/DX Host bridge (AGP disabled) (rev 03)
0000:00:07.0 ISA bridge: Intel Corporation 82371AB/EB/MB PIIX4 ISA (rev 01)
0000:00:07.1 IDE interface: Intel Corporation 82371AB/EB/MB PIIX4 IDE (rev 01)
0000:00:07.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 02)
0000:00:08.0 VGA compatible controller: Microsoft Corporation Hyper-V virtual VGA
0750:00:02.0 Infiniband controller: Mellanox Technologies MT27800 Family [ConnectX-5 Virtual Function]

**Comment by chadnar2** [comment]
So the InfiniBand card is present. Does 'lsmod |grep ib' show the InfiniBand modules are loaded?

**Comment by tbugfinder** [comment]
This is on Standard_NC24rs_v3:
```# lspci
0000:00:00.0 Host bridge: Intel Corporation 440BX/ZX/DX - 82443BX/ZX/DX Host bridge (AGP disabled) (rev 03)
0000:00:07.0 ISA bridge: Intel Corporation 82371AB/EB/MB PIIX4 ISA (rev 01)
0000:00:07.1 IDE interface: Intel Corporation 82371AB/EB/MB PIIX4 IDE (rev 01)
0000:00:07.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 02)
0000:00:08.0 VGA compatible controller: Microsoft Corporation Hyper-V virtual VGA
0001:00:00.0 3D controller: NVIDIA Corporation GV100GL [Tesla V100 PCIe 16GB] (rev a1)
0002:00:00.0 3D controller: NVIDIA Corporation GV100GL [Tesla V100 PCIe 16GB] (rev a1)
0003:00:00.0 3D controller: NVIDIA Corporation GV100GL [Tesla V100 PCIe 16GB] (rev a1)
0004:00:00.0 3D controller: NVIDIA Corporation GV100GL [Tesla V100 PCIe 16GB] (rev a1)
7cb1:00:02.0 Network controller: Mellanox Technologies MT27500/MT27520 Family [ConnectX-3/ConnectX-3 Pro Virtual Function]

```


lsmod:
```
# lsmod|grep -i ib|sort
devlink                60067  2 mlx4_ib,mlx4_core
ib_core               255469  2 mlx4_ib,ib_uverbs
ib_uverbs             102208  1 mlx4_ib
libata                243133  3 pata_acpi,ata_generic,ata_piix
libcrc32c              12644  2 xfs,nf_conntrack
mlx4_core             315896  1 mlx4_ib
mlx4_ib               179001  0

```

**Comment by tbugfinder** [comment]
I switched to HC44rs sku and ib0 has an IP address.

**Comment by edwardsp** [comment]
Closing this issue now although please reopen if you still have any problems
