### ISSUE TITLE
Error when trying to access script not referred by tags in config.json

### ISSUE THREAD

**Issue by AlexandreJean** [Azure/azurehpc#171]
Hello,

I report the following "bugs/behavior" of the az-build.
I have the following description in my config.json with only 2 tags loginnode and disable-selinux:
...
    "resources": {
        "jumpbox": {
            "type": "vm",
            "vm_type": "Standard_D4s_v3",
            "accelerated_networking": true,
            "public_ip": true,
            "image": "variables.hpc_image",
            "subnet": "admin",
            "tags": [
                "loginnode",
                "disable-selinux"
            ]
        }
    },
...
in the install section, I have the following:
"install": [
        {
            "script": "disable-selinux.sh",
            "tag": "disable-selinux",
            "sudo": true
        },
        {
            "script": "cndefault.sh",
            "tag": "cndefault",
            "sudo": true
        },
        {
            "script": "nfsserver.sh",
            "tag": "nfsserver",
            "sudo": true
        },
        {
            "script": "jumpbox.sh",
            "tag": "loginnode",
            "sudo": true
        }

When I am trying to run az-build it failed on :
Step 2 : cndefault.sh (jumpbox_script)
/home/vsts/work/1/s/azurehpc/libexec/install_helper.sh: line 294: azhpc_install_config.JumpBox/hostlists/tags/cndefault: No such file or directory
Error: (1) Errors while running azhpc_install_config.JumpBox/install/02_cndefault.sh
Wed Feb 19 21:02:13 UTC 2020 error : There were errors while running scripts, exiting

Thus, I decided to clean the non useful scripts in install section to avoid any unknown behavior.  
I can provide more detail if needed.
Thanks

**Comment by edwardsp** [comment]
This was fixed a while ago.  I'll close now but let me know if you still have problems.
