### ISSUE TITLE
Allow creating multiple VNETs within a single az-build

### ISSUE THREAD

**Issue by AlexandreJean** [Azure/azurehpc#178]
Hello,

In order to prepare the deployment of resources inside multiple VNET, it would be useful through the config JSON file to create multiple VNETs and tag after in the resource field which VNET we can assign to the VM or services for example.
Like this, we should be able to
1) Create the network infrastructure
2) Create resources inside the network
etc
Thanks,
Alex

**Comment by xpillons** [comment]
Unfortunately this is not possible in the current design with ARM. However you can create a VNET in a first deployment, and then use the '--no-vnet' option in later deployment to deploy resources and not the VNET. Just keep the vnet name and RG so that it can be referenced.
