### ISSUE TITLE
Dont overwrite auto_netappfiles_mount.sh if no ANF resources are in the config file

### ISSUE THREAD

**Issue by xpillons** [Azure/azurehpc#207]
The script auto_netappfiles_mount.sh is always overwritten even when no ANF resources are used. It means that you can't reused that script in other config file and chain deployments.

A typical scenario would be to 
 * Create ANF with config file 1
 * Build resources that mount ANF with config file 2

**Comment by edwardsp** [comment]
resolve with #208
