### ISSUE TITLE
azhpc-build - detect when a resource failed to be created

### ISSUE THREAD

**Issue by xpillons** [Azure/azurehpc#21]
If a resource built by azhpc-build failed to build, then the command wait until the default timeout (3600s). Reduce that timeout or detect any failures.
Typical error woud be not enough quota, or wrong password for windows VMs

**Comment by kanchanm** [comment]
@edwardsp fixed this with https://github.com/Azure/azurehpc/commit/2c6e03b9349b45d81eeec6e60c4dca77a74f5976
