### ISSUE TITLE
Default disk to Premium_LRS not compatible with VM size in config files

### ISSUE THREAD

**Issue by xpillons** [Azure/azurehpc#221]
With the latest update that default the OS and Data disks SKU to Premium_LRS there are VM size not supporting this settings in existing example config files. As a result these deployment failed.

**Comment by garvct** [comment]
Do you know which examples are failing?

**Comment by xpillons** [comment]
beegfs_local_ssd is one of these failing. Found last night the pipelines

**Comment by garvct** [comment]
Thanks will look at that now.

**Comment by edwardsp** [comment]
@garvct now we know why we only had standard SSD as the default ;-)

**Comment by garvct** [comment]
Also demonstrates why we need automated pipeline tests running and they should run before a PR is accepted (so we can catch these errors before PR gets merged into master)
