### ISSUE TITLE
$tmp_dir not set in 00_install_node_setup.sh

### ISSUE THREAD

**Issue by xpillons** [Azure/azurehpc#223]
$tmp_dir is used in the 00_install_node_setup.sh but never set
This variable is used in this line
prsync -p 50 -a -h hostlists/$tag ~/$tmp_dir ~ >> install/00_install_node_setup.log 2>&1

Is that expected to be empty or is there any missing args ?

**Comment by edwardsp** [comment]
fix pushed to master
