### ISSUE TITLE
install_wps_openmpi.sh fails

### ISSUE THREAD

**Issue by dazzag24** [Azure/azurehpc#238]
Having built WRF using install_wrf_openmpi.sh I moved onto builing WPS.

I had to modify install_wps_openmpi.sh to factor for the recent change the version 4.1.5 in install_wrf_openmpi.sh:

```
-WRF_VERSION=4.1.3
+WRF_VERSION=${WRF_VERSION:-4.1.3}
```
I then invoked it like so:

`SHARED_APP=$HOME/apps WRF_VERSION=4.1.5 SKU_TYPE=HBv2 ./install_wps_openmpi.sh`

and it gives this error:

`WPS-4.1/util/src/write_met_module.F
WPS-4.1/util/vertical_grid_38_20m_G3.txt
WPS-4.1/util/vertical_grid_50_20m_63km.txt
WPS-4.1/util/vertical_grid_70_20m_80km.txt
==> Error: Spec 'netcdf ^openmpi' matches no installed packages.
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'mpi/openmpi-4.0.2'
Will use NETCDF in dir: /home/deployer/apps/spack/HBv2/linux-centos7-skylake/gcc-9.2.0/netcdf-fortran-4.5.2-pb2rwfi5x4ut5idkryrlrmno7fctylyq

Error: The $WRF_DIR environment variable was set, but the WRF code at
       /home/deployer/apps/HBv2/wrf-openmp/WRF-4.1.5 doesn't appear to have been successfully compiled

Do 'configure' first
`

**Comment by dazzag24** [comment]
See https://github.com/Azure/azurehpc/pull/239 for a proposed fix.

**Comment by garvct** [comment]
Hi I updated WRF but not WPS, I will take a look and get back to you soon.

**Comment by garvct** [comment]
PR #239 looks good, just need to change the WRF version default to be 4.1.5. Once this is done I will merge.

**Comment by dazzag24** [comment]
Hi,

I have made the change to the default WRF_VERSION.

Thanks

Darren

**Comment by garvct** [comment]
Great, I have merged it into the master branch.
