### ISSUE TITLE
lfshsm.sh has region hard coded to westeurope

### ISSUE THREAD

**Issue by JonShelley** [Azure/azurehpc#28]
Line 60 in lfshsm.sh has region = westeurope. I'm guessing that this needs to be a variable. @edwardsp can you take a look at this?

**Comment by edwardsp** [comment]
It doesn't actually matter what it is set to as it's not used.  The Azure storage URL does not have the region in there.  We can probably remove but I need to check whether the lhsmd plugin fails if there isn't something present.
