### ISSUE TITLE
Check for json format (azcli)

### ISSUE THREAD

**Issue by garvct** [Azure/azurehpc#285]
azurehpc expects azcli will use the json format, but if you change the default format (i.e in azcli config file) to be different (e.g table or tsv) then azurehpc will not deploy and its not obvious from the error message what the problem is.

Suggestion
either check that the default azcli format  is json or explicitly set the format to json in all azcli options in azurehpc.

**Comment by edwardsp** [comment]
this should be fixed now @garvct

**Comment by edwardsp** [comment]
closing as this should be fixed
