### ISSUE TITLE
Custom scripts for a jumpbox

### ISSUE THREAD

**Issue by lmiroslaw** [Azure/azurehpc#286]
Hi Team,

My azhpc build command fails. Probably its a config error. Could you please give me a hint how to resolve it?

The 'install' section in my config.json looks like this:
`
"install": [
        {
            "script": "disable-selinux.sh",
            "tag": "disable-selinux",
            "sudo": true
        },
        {
            "script": "jumpbox.sh",
            "tag": "loginnode",
            "sudo": true
        }
`

Here is the output:
`
+ azhpc-build -c config.JumpBox.json
[2020-05-29 15:10:01] writing out arm template to deploy_config.JumpBox.json
[2020-05-29 15:10:01] creating resource group NVSTestRg01
[2020-05-29 15:10:03] deploying arm template
jumpbox         Microsoft.Compute/virtualMachines               OK
jumpbox_nic     Microsoft.Network/networkInterfaces             OK
jumpbox_pip     Microsoft.Network/publicIPAddresses             OK
hpcgateway      Microsoft.Network/virtualNetworks               OK
jumpbox_nsg     Microsoft.Network/networkSecurityGroups         OK
[2020-05-29 15:10:11] Provising succeeded
[2020-05-29 15:10:11] building host lists
[2020-05-29 15:10:11] building install scripts
[2020-05-29 15:10:13] Step 00 : install_node_setup.sh (jumpbox_script)
[2020-05-29 15:10:31]     duration: 18 seconds
[2020-05-29 15:10:31] Step 01 : disable-selinux.sh (jumpbox_script)
[2020-05-29 15:10:32]     duration: 1 seconds
[2020-05-29 15:10:32] Step 02 : jumpbox.sh (jumpbox_script)
**[2020-05-29 15:10:33] error: invalid returncode
    args=['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-i', 'hpcadmin_id_rsa', 'hpcadmin@jumpboxxxx.westeurope.cloudapp.azure.com', 'azhpc_install_config.JumpBox/install/02_jumpbox.sh', 'loginnode']
    return code=5
    stdout=
    stderr=Warning: Permanently added 'jumpboxxxx.westeurope.cloudapp.azure.com,1.1.1.1'** (ECDSA) to the list of known hosts.
`
It seems that there is a problem with logging in, however I can login hpcadmin@jumpboxxxx.westeurope.cloudapp.azure.com -i hpcadmin_id_rsa

jumpbox.sh script gets copied to the jumpbox.

Any hints what might be wrong?

**Comment by xpillons** [comment]
Is this still happening ? look for any erros in the azhpc_install_config.JumpBox/install/02_jumpbox.log file

**Comment by lmiroslaw** [comment]
Thanks @xpillons. That file helped to track the problem. Apparently, the privilliges of the scripts were not set. After 'chmod +x scripts/jumpbox.sh' the pipeline converges.
