### ISSUE TITLE
azhpc-resize deprecated?

### ISSUE THREAD

**Issue by jithinjosepkl** [Azure/azurehpc#346]
Is azhpc-resize deprecated now? Do we have an alternative command to scale up/down cluster?

**Comment by Smahane** [comment]
I'm curious as well.

**Comment by xpillons** [comment]
right now it is deprecated. to scale up/down clusters, use SLURM for which we have implemented the resume/start commands. We are evaluating how much effort and value to enable this scenario for PBS as well.
