### ISSUE TITLE
Cannot create a cluster from CentOS HPC 8.1 Internal VHD

### ISSUE THREAD

**Issue by souvik-de** [Azure/azurehpc#425]
**Describe the bug**
"azhpc-builld" fails at pbsserver.sh (step 09) when trying to create a cluster from an Internal CentOS 8.1 HPC VHD. Observation drawn from multiple attempts.

**To Reproduce**
1. Download VHD to a storage account and create an Image.
2. Use the resource (image) in azhpc scripts to deploy a cluster

**Expected behavior**
1. Deployment should be successful

**Screenshots**
![image](https://user-images.githubusercontent.com/69217314/100675271-7f6e4a00-331b-11eb-8cae-63fbb19138d7.png)

**Configuration (please complete the following information):**
 - OS and version: CentOS 8.1 HPC Internal

**Comment by souvik-de** [comment]
I don't think that this is specifically for the internal image but 8.1 in general

**Comment by xpillons** [comment]
Thank you for raising this issue. As of today we don't support CentOS 8.1. In the meantime, you can copy the pbsserver.sh script in your own scripts directory and update it for 8.1. You may want to use PBS 20 as 19 doesn't support 8.1.
