### ISSUE TITLE
[bug]anf-full pipeline time out on deployment

### ISSUE THREAD

**Issue by brsiglar** [Azure/azurehpc#436]
**Describe the bug**
Running anf-full pipeline, there is an issue with step 0 timing out.

**To Reproduce**
1. Go to 'https://azurecat.visualstudio.com/hpccat/_build?definitionId=287&_a=summary'
2. Click on 'Run Pipeline'
3. Scroll down to 'Build Cluster'
4. Time out "[2020-12-21 17:43:04] Step 00 : install_node_setup.sh (jumpbox_script)"

**Expected behavior**

**Screenshots**

**Configuration (please complete the following information):**
 - OS and version: [e.g. Windows 10 1909]
 - Context of execution : [WSL, WSL2, CloudShell, ...]

**Additional context**

**Comment by xpillons** [comment]
It happens too here https://azurecat.visualstudio.com/hpccat/_build/results?buildId=10304&view=logs&j=6e4f1cc6-8050-5bf9-8495-3efafd6ef526&t=d55b938c-7420-5d64-4f01-a655a6be2261&l=733
Seems to be an infinite loop when applying the step00.

**Comment by xpillons** [comment]
Closed by #437
