### ISSUE TITLE
cc timeout in cc_anf: cycle_start_cluster.sh

### ISSUE THREAD

**Issue by bmoxon** [Azure/azurehpc#438]
https://azurecat.visualstudio.com/hpccat/_build/results?buildId=10356&view=logs&j=6e4f1cc6-8050-5bf9-8495-3efafd6ef526&t=02c4ec7d-6fd1-55ff-e3bf-c3487fccf8a6&l=55

Timeout in /bin/bash /azp/agent/_work/_temp/azureclitaskscript1609028605601.sh
Last script breadcrumb "apps/ci/cycle_start_cluster.sh pbscycle"

**Comment by xpillons** [comment]
Closed by PR #446 
Fixing wrong external NFS options in CC template
