### ISSUE TITLE
[bug] Slum_autoscale pipeline failed with headnode connnection refused.

### ISSUE THREAD

**Issue by cperi** [Azure/azurehpc#449]
Pipeline build resources failed -
https://azurecat.visualstudio.com/hpccat/_build/results?buildId=10436&view=logs&j=6e4f1cc6-8050-5bf9-8495-3efafd6ef526&t=d55b938c-7420-5d64-4f01-a655a6be2261

[2021-01-10 00:13:36] building install scripts
[2021-01-10 00:13:38] error: invalid returncode
    args=['rsync', '-a', '-e', 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i hpcadmin_id_rsa', 'azhpc_install_config', 'hpcadmin@headnode3594f4.eastus.cloudapp.azure.com:.']
    return code=255
    stdout=
    stderr=ssh: connect to host headnode3594f4.eastus.cloudapp.azure.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(235) [sender=3.1.2]

**Comment by xpillons** [comment]
Closed by PR #452
