### ISSUE TITLE
post_cyclevm.sh dependency on unzip

### ISSUE THREAD

**Issue by kanchanm** [Azure/azurehpc#46]
https://github.com/Azure/azurehpc/blob/master/scripts/post_cyclevm.sh has dependency on unzip and fails as it is not present in some case. it failed for me when using ubuntu shell (not sure if it is present in cloudshell too).

**Comment by xpillons** [comment]
cloudshell and CentOS have unzip by default installed

**Comment by xpillons** [comment]
added unzip as a pre-requ in the pre-requisite tutorial document
