### ISSUE TITLE
[bug] NFS mount fails due issues in nfs.conf

### ISSUE THREAD

**Issue by cperi** [Azure/azurehpc#471]
**Describe the bug**
While deploying in the gov region using Centos 7.7 and Centos 7.8, noticed that nfs client will not mount the shared directory. It seems that the following line is causing an error.

Line#44 in the /etc/nfs.conf file is 
     40 # storagedir=/var/lib/nfs/nfsdcltrack
     41 #
     42 #[nfsd]
     43 # debug=0
     44 threads=32
     45 # host=
     46 # port=0
     47 # grace-time=90

**Expected behavior**
Home directories and data and apps will not mount.

**Screenshots**
Feb 19 20:36:10 headnode systemd[1]: Starting NFS server and services...
Feb 19 20:36:10 headnode exportfs[4305]: exportfs: config file error: line 44: ignoring line due to no section
Feb 19 20:36:10 headnode rpc.nfsd[4308]: : config file error: line 44: ignoring line due to no section
Feb 19 20:36:10 headnode systemd[1]: Started NFS server and services.

**Configuration (please complete the following information):**

**Additional context**
I was able to workaround this issue by commenting out the line in the nfs.conf file -

The recent change in nfs tune section in the scripts "install-nfsserver.sh" is causing the issue !!

########################################
# Tune NFS
########################################

cores=$(grep processor /proc/cpuinfo | wc -l)
nfs_proc=$(($cores * 4))
replace="s/# threads=8/threads=$nfs_proc/g"
sed -i -e "$replace" /etc/nfs.conf

systemctl restart nfs-server

**Comment by xpillons** [comment]
I was not able to repro the error, however the [nfsd] section is commented but default. I will uncomment it in the install-nfsserver.sh script
