### ISSUE TITLE
support cyclecloud8 in cc_install.sh

### ISSUE THREAD

**Issue by tbugfinder** [Azure/azurehpc#496]
Hello,

would it make sense to support cyclecloud8 installer python in cc_install.sh script?
https://github.com/Azure/azurehpc/blob/1adbceb6dac2151b5cffd76cc837482245fc42fa/scripts/cc_install.sh#L13

Maybe the goal of cc_install.sh script is different than I think of :-)

Thanks & Best

**Comment by xpillons** [comment]
Please use https://github.com/Azure/azurehpc/blob/master/scripts/cyclecloud8_install.py instead.

**Comment by tbugfinder** [comment]
https://github.com/Azure/azurehpc/blob/master/scripts/cyclecloud8_install.py#L506

Why is the installation commented?

**Comment by xpillons** [comment]
This is designed to run on top of the CycleCloud marketplace image. Please look at the ./examples/cycleserver_msi example.
