### ISSUE TITLE
Config file compatibility broken with az cli fix

### ISSUE THREAD

**Issue by edwardsp** [Azure/azurehpc#66]
The unit was changed to GB in the bugfix for the az cli changing and only the anf_full was updated.  Please can we keep the ANF so that pools and volumes are in 1TB units in the config file?

**Comment by garvct** [comment]
The official netapps az cli has  the pools unit is TiB and the volume unit in GiB, should we not have the config file use the same units?

**Comment by edwardsp** [comment]
It used to be bytes but we created a config file and had TiB to simplify things.  The issue I have is this was pushed as a bug fix but we broke compatibility with the config file.  Changing the config file should be discussed as a feature as we have our own projects outside of this repo which will break.
